### ISSUE TITLE
RuntimeWarning: invalid value encountered in greater return (self.a < x) & (x < self.b)

### ISSUE THREAD

**Issue by bioguy2018** [scverse/scanpy#674] opened 2019-06-02 16:29 UTC
Hello everyone,
I have faced the below warning messages during running `sc.tl.rank_genes_groups` with parameters t-test and t-test overestimated.

> RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)

> RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)

> RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)

I found exactly the same warning message in a forum but there the warning message was coming from auto-sklearn package and since there is no auto-sklearn used in scanpy and instead we got scikit-learn I am wondering is it a problem with the version that I am using or is it a bug from scikit or scanpy it self

my versions are:

> scanpy==1.4.3 anndata==0.6.20 umap==0.3.8 numpy==1.16.3 scipy==1.2.1 pandas==0.23.4 scikit-learn==0.20.3 statsmodels==0.9.0 python-igraph==0.7.1+4.bed07760 louvain==0.6.1

**Comment by ivirshup** [comment] 2019-06-06 09:23
If you remove genes whose values are all zero, do you still get the warning?

If so, this might be a duplicate of #629.

**Comment by ivirshup** [comment] 2019-06-06 13:10
Closed via #683

**Comment by bioguy2018** [comment] 2019-06-06 14:33
@ivirshup Thanks a lot for your reply....I already have removed all genes that are not expressed at all through filtering part so I doubt if that is the problem

**Comment by ivirshup** [comment] 2019-06-08 09:53
Could you provide a small example that triggers the warning you're getting? If possible, could you also try it using the master branch of scanpy?

**Comment by ivirshup** [comment] 2021-01-25 01:46
I'm pretty sure this has been fixed. I believe the issue was that some groups would have zero expression for a particular gene which would trigger a warning when calculating within group variance. Please let us know if this hasn't been resolved.

**Closed as completed by ivirshup** 2021-01-25 01:46 UTC
Labels: Area – Differential Expression, Needs info❔
