### ISSUE TITLE
Can I make a deep copy of the scanpy object?

### ISSUE THREAD

**Issue by chansigit** [scverse/scanpy#1239] opened 2020-05-21 03:52 UTC
I subseted the scanpy object to view some subpopulations. But I was amazed that whether conducting deep copy yields different results.

Here are the snippets: 

#VERSION 1:
import copy
Tcells= copy.copy(adata[adata.obs["Leiden0.7"].isin(["2","3","8","15"])]  )
sc.tl.pca(Tcells, svd_solver='arpack',n_comps=50)
sc.pp.neighbors(Tcells, n_neighbors=10, n_pcs=40)
sc.tl.umap(Tcells, min_dist=0.2, random_state=42)
sc.pl.umap(Tcells,color=["Leiden0.7"])

#VERSION 2:
import copy
Tcells= adata[adata.obs["Leiden0.7"].isin(["2","3","8","15"])]  
sc.tl.pca(Tcells, svd_solver='arpack',n_comps=50)
sc.pp.neighbors(Tcells, n_neighbors=10, n_pcs=40)
sc.tl.umap(Tcells, min_dist=0.2, random_state=42)
sc.pl.umap(Tcells,color=["Leiden0.7"])

The two VERSIONS of snippet just give different umaps (even though I fixed the random seed), and different number of clusters (that's unacceptable, as far as I know, clustering is based on PCs).

#### Versions:
scanpy==1.4.5.post1 anndata==0.7.1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.1 statsmodels==0.11.1 python-igraph==0.8.0

So should I make a deep copy of the scanpy object? It looks like deep copy ruined something in the object.

**Comment by chansigit** [comment] 2020-05-21 04:28
I found that after doing deep copy, sc.tl.pca doesn't change the PC values in the object, which may affect the downstream umap and Leiden clustering. 

But why? I thought a deep copied object was supposed to behave the same as the non-deep copy one.

**Comment by ivirshup** [comment] 2020-05-21 08:12
Copying using the `copy` module is a bit ill defined for `AnnData` objects currently. This has to do with some internals of how we do views of arrays. In general I'd recommend doing copies via `adata.copy()`, which performs a deep copy.

But it looks like there might be another problem with the PCA not being exactly reproducible. After a fair amount of checking that it was exactly reproducible, it looks like we forgot to actually pass the random seed... There has been fixed, and there will be a bug-fix release soon (#1240).

This still does not fix the issue of reproducibility if you've made a shallow copy of a AnnData view with `copy`. I'll have to look into this a bit more.

**Comment by ivirshup** [comment] 2020-05-21 08:53
The release with PCA bug fix is now on pypi

**Comment by ivirshup** [comment] 2020-05-21 09:28
Hmm. Did your original object already have a pca computed on it? I'm not sure if the values in `obsm` would have been updated when you made a shallow copy with `copy`.

**Comment by mariaasierra** [comment] 2022-02-04 23:10
I am having a similar issue.I try to copy the AnnData object with adata.copy() but it tells me 
TypeError: cannot unpack non-iterable NoneType object

I would like to copy the observations that match a criteria. 
adata_subset[i] = adata[adata.obs['column']==i].copy()

Any advice?

**Comment by ivirshup** [comment] 2022-02-07 12:33
@mariaasierra could you open a new issue for this on the anndata repo? A full traceback and versions of software would also be useful.

I'm going to close this issue since it's quite old, I believe should be solved, and I think unrelated to what @mariaasierra is seeing.

**Closed as completed by ivirshup** 2022-02-07 12:33 UTC
