### ISSUE TITLE
code that worked months ago not working anymore?

### ISSUE THREAD

**Issue by dm8000** [scverse/scanpy#1925] opened 2021-07-05 20:17 UTC
Hello

I wrote this code months ago and it worked fine. However it is not working anymore. I did not change one line and it is the exact same object. 

This is what my object looks like

```
AnnData object with n_obs × n_vars = 89706 × 34717
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'timpoint', 'condition', 'timpoint.condition', 'CellTypeRefined', 'CellTypeRefined.Rajbhandari', 'Sample.type', 'Treatment', 'Author'
    var: 'features'
```

This is the code

```
#calcular e visualizar metricas de QC por estudo
sc.pp.calculate_qc_metrics(adata, expr_type='counts', var_type='genes', qc_vars=(), 
                           percent_top=None, layer=None, use_raw=False, inplace=True, 
                           log1p=False, parallel=None)
adata.var['mt'] = adata.var_names.str.startswith('mt')
sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)
adata.var['rp'] = adata.var_names.str.startswith('Rps', 'Rpl')
sc.pp.calculate_qc_metrics(adata, qc_vars=['rp'], percent_top=None, log1p=False, inplace=True)
sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mt', 'pct_counts_rp'], groupby = 'Author', jitter=0.4, multi_panel=True)



Benitez = adata[adata.obs['Author'].isin(['Benitez'])]
Rajbhandari = adata[adata.obs['Author'].isin(['Rajbhandari'])]
Sun = adata[adata.obs['Author'].isin(['Sun'])]

sc.pl.scatter(Benitez, x='total_counts', y='pct_counts_mt')
sc.pl.scatter(Benitez, x='total_counts', y='n_genes_by_counts')

sc.pl.scatter(Rajbhandari, x='total_counts', y='pct_counts_mt')
sc.pl.scatter(Rajbhandari, x='total_counts', y='n_genes_by_counts')

sc.pl.scatter(Sun, x='total_counts', y='pct_counts_mt')
sc.pl.scatter(Sun, x='total_counts', y='n_genes_by_counts')

```

And this is the error

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'total_counts'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/frame.py in _set_item_mgr(self, key, value)
   3745         try:
-> 3746             loc = self._info_axis.get_loc(key)
   3747         except KeyError:

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 

KeyError: 'total_counts'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-3-69925a75d466> in <module>
      1 #calcular e visualizar metricas de QC por estudo
----> 2 sc.pp.calculate_qc_metrics(adata, expr_type='counts', var_type='genes', qc_vars=(), 
      3                            percent_top=None, layer=None, use_raw=False, inplace=True,
      4                            log1p=False, parallel=None)
      5 adata.var['mt'] = adata.var_names.str.startswith('mt')

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py in calculate_qc_metrics(adata, expr_type, var_type, qc_vars, percent_top, layer, use_raw, inplace, log1p, parallel)
    304         X.eliminate_zeros()
    305 
--> 306     obs_metrics = describe_obs(
    307         adata,
    308         expr_type=expr_type,

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py in describe_obs(adata, expr_type, var_type, qc_vars, percent_top, layer, use_raw, log1p, inplace, X, parallel)
    133         )
    134     if inplace:
--> 135         adata.obs[obs_metrics.columns] = obs_metrics
    136     else:
    137         return obs_metrics

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   3595             self._setitem_frame(key, value)
   3596         elif isinstance(key, (Series, np.ndarray, list, Index)):
-> 3597             self._setitem_array(key, value)
   3598         elif isinstance(value, DataFrame):
   3599             self._set_item_frame_value(key, value)

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/frame.py in _setitem_array(self, key, value)
   3634                 check_key_length(self.columns, key, value)
   3635                 for k1, k2 in zip(key, value.columns):
-> 3636                     self[k1] = value[k2]
   3637 
   3638             elif not is_list_like(value):

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   3605         else:
   3606             # set column
-> 3607             self._set_item(key, value)
   3608 
   3609     def _setitem_slice(self, key: slice, value):

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/frame.py in _set_item(self, key, value)
   3790                     value = np.tile(value, (len(existing_piece.columns), 1)).T
   3791 
-> 3792         self._set_item_mgr(key, value)
   3793 
   3794     def _set_value(

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/frame.py in _set_item_mgr(self, key, value)
   3747         except KeyError:
   3748             # This item wasn't present, just insert at end
-> 3749             self._mgr.insert(len(self._info_axis), key, value)
   3750         else:
   3751             self._iset_item_mgr(loc, value)

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/internals/managers.py in insert(self, loc, item, value)
   1153             value = ensure_block_shape(value, ndim=self.ndim)
   1154 
-> 1155         block = new_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
   1156 
   1157         for blkno, count in _fast_count_smallints(self.blknos[loc:]):

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/internals/blocks.py in new_block(values, placement, ndim, klass)
   1920 
   1921     values, _ = extract_pandas_array(values, None, ndim)
-> 1922     check_ndim(values, placement, ndim)
   1923 
   1924     if klass is None:

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/pandas/core/internals/blocks.py in check_ndim(values, placement, ndim)
   1962             )
   1963         if len(placement) != len(values):
-> 1964             raise ValueError(
   1965                 f"Wrong number of items passed {len(values)}, "
   1966                 f"placement implies {len(placement)}"

ValueError: Wrong number of items passed 89706, placement implies 1
```

**Comment by ivirshup** [comment] 2021-07-05 23:19
There's currently an bug with pandas 1.3 breaking assignment here. Should be fix out soon.

Closing as duplicate of #1917.

**Closed as duplicate** 2021-07-05 23:19 UTC
