### ISSUE TITLE
sc.tl.PAGA error: object of type 'numpy.float64' has no len()

### ISSUE THREAD

**Issue by klprint** [scverse/scanpy#695] opened 2019-06-19 06:53 UTC
After studying the PAGA tutorial, I tried to apply it to my data (40,000 cells, 8,000 highly variable genes).

I ran the following commands:
```python
sc.pp.neighbors(adata_hvg)
sc.tl.louvain(adata_hvg)
sc.tl.draw_graph(adata_hvg)
```
Till here, everything works nicely, but then I try to get the PAGA representation:

```python
sc.tl.paga(adata_hvg, groups="louvain")
```

This returns the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-249-7cc787ba28f9> in <module>
----> 1 sc.tl.paga(adata_hvg, groups="louvain")

~/miniconda3/envs/wot/lib/python3.6/site-packages/scanpy/tools/_paga.py in paga(adata, groups, use_rna_velocity, model, copy)
     93         adata.uns['paga'] = {}
     94     if not use_rna_velocity:
---> 95         paga.compute_connectivities()
     96         adata.uns['paga']['connectivities'] = paga.connectivities
     97         adata.uns['paga']['connectivities_tree'] = paga.connectivities_tree

~/miniconda3/envs/wot/lib/python3.6/site-packages/scanpy/tools/_paga.py in compute_connectivities(self)
    127     def compute_connectivities(self):
    128         if self._model == 'v1.2':
--> 129             return self._compute_connectivities_v1_2()
    130         elif self._model == 'v1.0':
    131             return self._compute_connectivities_v1_0()

~/miniconda3/envs/wot/lib/python3.6/site-packages/scanpy/tools/_paga.py in _compute_connectivities_v1_2(self)
    161             if scaled_value > 1:
    162                 scaled_value = 1
--> 163             connectivities[i, j] = scaled_value
    164             expected_n_edges[i, j] = expected_random_null
    165         # set attributes

~/miniconda3/envs/wot/lib/python3.6/site-packages/scipy/sparse/_index.py in __setitem__(self, key, x)
     67             if x.size != 1:
     68                 raise ValueError('Trying to assign a sequence to an item')
---> 69             self._set_intXint(row, col, x.flat[0])
     70             return
     71 

~/miniconda3/envs/wot/lib/python3.6/site-packages/scipy/sparse/compressed.py in _set_intXint(self, row, col, x)
    795     def _set_intXint(self, row, col, x):
    796         i, j = self._swap((row, col))
--> 797         self._set_many(i, j, x)
    798 
    799     def _set_arrayXarray(self, row, col, x):

~/miniconda3/envs/wot/lib/python3.6/site-packages/anndata/h5py/h5sparse.py in _set_many(self, i, j, x)
    176     i, j, M, N = self._prepare_indices(i, j)
    177 
--> 178     n_samples = len(x)
    179     offsets = np.empty(n_samples, dtype=self.indices.dtype)
    180     ret = _sparsetools.csr_sample_offsets(M, N, self.indptr, self.indices,

TypeError: object of type 'numpy.float64' has no len()
```
I would be happy about any suggestions.

Keep up the nice work!

Kevin

**Comment by LuckyMD** [comment] 2019-06-19 08:39
Hi,

This might have to do with scipy 1.3.0. If you downgrade to 1.2.1 this should work for the moment. Scipy 1.3.0 compatibility is being fixed atm.

**Comment by flying-sheep** [comment] 2019-06-19 08:58
duplicate of theislab/anndata#159

**Closed as duplicate by flying-sheep** 2019-06-19 08:58 UTC
