### ISSUE TITLE
Do not change matplotlib style parameters

### ISSUE THREAD

**Issue by vals** [scverse/scanpy#108] opened 2018-03-20 18:20 UTC
When loading scanpy through `import scanpy.api as sc` the plotting style is changed. This prevents my from using it in my general workflow because I have particular plotting styles I use.

This used to be a issue with seaborn, but was changed in version 0.8, but scanpy still seems to restyle the entire plotting environment?

If styles are applied locally in particular plotting functions, that is fine, but it shouldn't affect the users other plots.

**Comment by falexwolf** [comment] 2018-03-20 23:45
Yes, agreed.

You can currently workaround with [set_rcParams_Defaults](https://scanpy.readthedocs.io/en/latest/api/scanpy.api.pl.set_rcParams_Defaults.html). Upon import, [set_rcParams_Scanpy](https://scanpy.readthedocs.io/en/latest/api/scanpy.api.pl.set_rcParams_Scanpy.html) is automatically called.

I had the impression that seaborn still changes the rcParams also after 0.8. If it doesn't I can remove the hack of resetting the params after calling `seaborn.violinplot` for the first time.

I agree that in Scanpy 1.0, we should remove the automatic call of set_rcParams_Scanpy and instead require this from the user.

**Comment by vals** [comment] 2018-03-20 23:51
Great! Thanks! :)

Just doing a quick check, it doesn't seem like Seaborn affects things:
![image](https://user-images.githubusercontent.com/668803/37688750-cc1b3d70-2c5e-11e8-937e-f40c6c1776e3.png)

Scanpy on the other hand makes the text larger and puts in a grid.

**Comment by falexwolf** [comment] 2018-03-20 23:54
Hm, yes, such behavior is really frustrating. I was probably using old seaborn versions when coming up with the brilliant idea of fighting back its annoying behavior by building the same annoying behavior into scanpy.

Will be resolved in 1.0. Thank you for pointing it out again.

**Comment by falexwolf** [comment] 2018-03-21 00:50
Fixed in https://github.com/theislab/scanpy/commit/57161ec444eef7815e159037c6944ddcc75572d9

However, the version1 branch is not stable yet... another day or two...

What made me believe that seaborn is still doing strange things, is this... one call to `seaborn.set_style` messes up the whole configuration... That's a bug, isn't it?
<img width="207" alt="image" src="https://user-images.githubusercontent.com/16916678/37690247-05c2686e-2caa-11e8-8dc2-7365a90f8748.png">

**Comment by falexwolf** [comment] 2018-03-21 00:52
Ah ok, just looked it up. It's not a bug... :wink: I don't know why I misunderstood this... Must have been a long time ago...

**Comment by vals** [comment] 2018-03-21 17:50
Mm I think I you're supposed to use a context (`with ... :`) to avoid changing things globally.

Anyway my current workaround of doing `from scanpy.api import preprocessing as scpp` is not too cumbersome, so should be okay until 1.0 hits :)

**Comment by falexwolf** [comment] 2018-04-11 10:40
Scanpy 1.0 is out and hence I can close this, I guess.

**Closed as completed by falexwolf** 2018-04-11 10:40 UTC
