### ISSUE TITLE
ResolvePackageNotFound:   - louvain   - bioconductor-rhdf5lib /Also CondaEnvException: Pip failed

### ISSUE THREAD

**Issue by JayalalKJ** [scverse/scanpy#1220] opened 2020-05-14 12:36 UTC
Hi
I'm facing an installation issue. The issues are explained below
I got failed to install **louvain   and bioconductor-rhdf5lib**  from paga_project_environment.yml (See file contents below).

Using Window 10 

> conda env create -f .\sc_tutorial_environment.yml**   
error **CondaEnvException: Pip failed**

Please find .yml file from here https://github.com/theislab/single-cell-tutorial

**Comment by giovp** [comment] 2020-10-01 20:18
it's not clear what the problem here sorry, can you copy the error and report a reproducible example? thank you!
I'll close this for now, feel free to reopen

**Closed as completed by giovp** 2020-10-01 20:18 UTC

**Comment by JayalalKJ** [comment] 2020-10-01 21:15
Hi
 Please reopen this case

**Comment by giovp** [comment] 2020-10-02 06:25
Hi @JayalalKJ ,
as you also pointed out, this issue is related to an environment in https://github.com/theislab/single-cell-tutorial
It's best if you open an issue there and directly address maintainers of that repo. 
Beside that, we can't really help you in this case because we don't have enough information on the error and also it relates to an external package. We could provide you with more help if you post the complete error log, but pls do so not here but in the other repo.
Hope this is helpful

**Comment by LuckyMD** [comment] 2020-10-02 10:16
This looks like you can't find the louvain package via `conda` on windows. I believe that's a known issue that we've encountered before in the scanpy issues. See for example #786
