### ISSUE TITLE
Go back to tutorial submodule

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#2636] opened 2023-08-24 11:12 UTC
### What kind of feature would you like to request?

Other?

### Please describe your wishes

The tutorial submodule was removed as part of a fix-up pass over the docs by @flying-sheep.

The issue at the time was warnings which weren't immediately obvious how to fix.

Since there are a number of reasons to prefer the submodule approach over a separate scanpy-tutorials website, I would like to bring it back.

The plan is: bring back the submodule. In this PR I'll see if the warnings can be easily fixed. If they can't, they'll be silenced and an issue tracking fixing them for the next release will be opened.

**Comment by flying-sheep** [comment] 2023-08-24 11:33
Let’s coordinate here and come up with what we think is the best strategy:

- @grst and me thought both are fine solutions, that’s why we closed https://github.com/scverse/scanpy-tutorials/issues/64, let’s update that one with what we come up with
- I think the main discussion should happen in https://github.com/scverse/cookiecutter-scverse/issues/40, then we close this issue when we implemented that for scanpy

**Comment by ivirshup** [comment] 2023-08-24 11:36
Since we already made the decision to use a submodule in scanpy (why it was that way) I don't think we need to discuss more before going back to it. Still happy to have discussions about better ways to do things, but we've already established a setup and workflow.

**Comment by flying-sheep** [comment] 2023-08-24 12:07
Sure, I just suggested that since I don‘t feel like it’s worth the effort:

1. submodules are a temporary solution (to be replaced by the one we’ll settle on in the linked issue)
2. the current solution works well enough (intersphinx makes sure links are valid and have a nice default text)

If you feel it’s important enough to switch to it for the next few weeks, it would be nice to settle on a canonical URL for each of the tutorials, i.e. that the tutorials on https://scanpy-tutorials.readthedocs.io redirect to the ones on https://scanpy.readthedocs.io. Otherwise some people will link to one version, others to the other.

**Comment by flying-sheep** [comment] 2024-01-22 13:43
After @ilan-gold mentioned that scanpy’s tutorials are actually not reproducible, I made an issue for that: https://github.com/scverse/scanpy-tutorials/issues/79

Maybe we need to address that before the release, that’ll also get rid of the warnings.

If you need to suppress them, I think this extension could be an acceptable solution: https://github.com/picnixz/sphinx-zeta-suppress

**Closed as completed** 2024-03-26 16:04 UTC
Labels: Area - Documentation 📒, Development Process 🚀
