### ISSUE TITLE
Can't import scanpy after torch

### ISSUE THREAD

**Issue by alirezaomidi** [scverse/scanpy#1286] opened 2020-06-17 21:29 UTC
I have `pytorch` and `scanpy` installed inside a conda environment. When I want to import scanpy **after** torch, the import won't finish. The interesting part is that importing scanpy before torch is possible! For example, this code takes a long time and probably does not finish:

```python
import torch
import scanpy
```

But the following example works:

```python
import scanpy
import torch
```

#### Versions:

> scanpy==1.5.1 anndata==0.7.3 umap==0.4.4 numpy==1.18.5 scipy==1.4.1 pandas==1.0.5 scikit-learn==0.23.1 statsmodels==0.11.1 pytorch==1.1.0 torchvision==0.3.0

**Comment by ivirshup** [comment] 2020-06-19 06:16
I'm not able to reproduce this. Here's what I tried

* Made a conda environment with `conda create -yn torch-scanpy "python=3.8"`, and activated it `conda activate torch-scanpy`
* Installed: `pip install scanpy torch`
* Imported: `python3 -c "import torch; import scanpy"`

IIRC, there has been an issue with the order of importing numba and pytorch due to how they require their LLVM dependency.  I would make sure your version of pytorch and numba are up to date (I believe your pytorch is a few versions old) and trying again. If the issue persists, could you check if you run into problems with this?

```python
import torch
import numba
```

**Comment by giovp** [comment] 2020-10-01 20:04
I have pytorch and tensorflow alongside scanpy in several conda envs. I would close this for now, also because it's not clear what "probably it does not finish" means. 
Feel free to reopen it if problem persists.

**Closed as completed by giovp** 2020-10-01 20:04 UTC
Labels: Needs info❔
