### ISSUE TITLE
trouble using read_visium with visium ST data on windows 

### ISSUE THREAD

**Issue by jeffgehlhausen** [scverse/scanpy#2488] opened 2023-05-14 19:01 UTC
Hello - I am trying to use scanpy to load visium ST data.  The tissue_positions.csv file is located in the spatial folder - I renamed it to tissue_positions_list.csv per the expectation of scanpy but I continue to get the following error.  I have confirmed that the folder structure and pathing is correct.  Can you think of what else could be the issue with it not reading/finding this file?  

```py
>>> import os
>>> # p = os.path.join( "path to outs location")
>>> print(p)
"path to outs location"
>>> print(os.path.exists(p))
True
>>> ad = sc.read_visium(p)
```

```pytb
Traceback (most recent call last):

  Cell In[6], line 1
    ad = sc.read_visium(p)

  File ~\anaconda3\lib\site-packages\scanpy\readwrite.py:390 in read_visium
    raise OSError(f"Could not find '{f}'")

OSError: Could not find 'path to outs location\spatial\tissue_positions_list.csv'
```

### Session/scanpy info:
Software versions
Python 3.10.9 64bit [MSC v.1916 64 bit (AMD64)]
IPython 8.10.0
OS Windows 10 10.0.22621 SP0
scanpy 1.9.3
Sun May 14 14:59:57 2023 Eastern Daylight Time

**Comment by jjxia955** [comment] 2023-05-26 18:12
in the outs/spatial file, change the tissue_positions.csv to tissue_positions_list.csv, it should work out

**Comment by jhaberbe** [comment] 2023-07-25 23:24
This is updated in the newest version of the module, where it looks for either `tissue_positions.csv` or `tissue_positions_list.csv`. The code on the github project works, but unfortunately the most recent version on PyPi was from Mar 2, 2023. 

An easy fix is to download the github project directly, using something like 
`pip install git+https://github.com/scverse/scanpy.git#egg=scanpy`

I did it recently in a Google Colaboratory Notebook with a file with `tissue_positions.csv`, and it worked.

**Comment by mattcai10x** [comment] 2023-07-27 04:52
> in the outs/spatial file, change the tissue_positions.csv to tissue_positions_list.csv, it should work out

Doing this will cause issues when you try to spatially plot the data because the coordinates dtype is a string instead of int. You have to also do this suggestion after: https://github.com/scverse/squidpy/issues/623#issuecomment-1339403351

It would be great if the next scanpy release included the read_visium() update or revisit the idea to [remove it in scanpy in favor of squidpy](https://github.com/scverse/scanpy/issues/2331).

**Comment by flying-sheep** [comment] 2023-07-27 12:08
duplicate of #2345, #2565, and so on

we’ll do a release soon

**Closed as completed by flying-sheep** 2023-07-27 12:08 UTC

**Comment by jhaberbe** [comment] 2023-07-27 18:14
awesome, thanks!
