### ISSUE TITLE
Feels it might be better to using absolute path and names

### ISSUE THREAD

**Issue by hansen7** [scverse/scanpy#2360] opened 2022-10-24 07:09 UTC
...
Hi there, thanks for the contribution. I feel it would be better if we can self-define the absolute name and paths when saving the figures.
https://github.com/scverse/scanpy/blob/e5cdbbc02702d779352cbbdfa8e54020d93301ea/scanpy/plotting/_tools/__init__.py#L432

**Comment by hansen7** [comment] 2022-10-24 07:29
It is true that we can use functions such as `os.rename()` to move the generated figures right after, but the prefix format (herein `writekey`) is not fixed:

https://github.com/scverse/scanpy/blob/e5cdbbc02702d779352cbbdfa8e54020d93301ea/scanpy/plotting/_tools/__init__.py#L432

https://github.com/scverse/scanpy/blob/e5cdbbc02702d779352cbbdfa8e54020d93301ea/scanpy/plotting/_tools/__init__.py#L1201-L1205

**Comment by Zethson** [comment] 2022-10-27 21:29
I'll close this as duplicate of https://github.com/scverse/scanpy/issues/2324

**Closed as completed by Zethson** 2022-10-27 21:29 UTC
