### ISSUE TITLE
Issue with tl.pca following scaling

### ISSUE THREAD

**Issue by rgranit** [scverse/scanpy#2163] opened 2022-03-02 11:35 UTC
scanpy==1.8.2

Hi,

I'm attempting to cluster subset of B-cells:

```python 
B=ad[ad.obs['clusters'].isin(['B-cell']),:].copy()
sc.pp.scale(B)
sc.tl.pca(B, svd_solver='arpack')
```

Yet I encounter an error:
`ValueError: Input contains NaN, infinity or a value too large for dtype('float32').`

When I don't scale the data the error doe not occur.. any suggestions? I supposed that after taking a subset rescaling is needed for these cells.

Thanks!

**Comment by ivirshup** [comment] 2022-03-21 18:15
Hi @rgranit. 

Does B.X contain `NaN` or infinite values after you rescale? Could you show us the repr for `ad` and `B` as well?

It would also be great if you could either make a small example that reproduces this, or if you could share the data somehow.

**Comment by eroell** [comment] 2023-10-12 09:34
We will close the issue for now, hopefully you obtained the expected behaviour :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)

**Closed as not planned by eroell** 2023-10-12 09:34 UTC
Labels: Needs info❔, Closing candidate

**Comment by sophiamaedler** [comment] 2024-06-26 13:00
I also recently encountered this issue. I've dug into the problem a little bit and for me the cause seems to be that the sc.pp.scale function introduces the NaN values. This occurs for columns which show very little variance and are almost constant.

According to the current documentation this should not be the current expected behaviour though and should only (possibly) occur in future versions: 

`Variables (genes) that do not display any variation (are constant across all observations) are retained and (for zero_center==True) set to 0 during this operation. In the future, they might be set to NaNs.`

So I'm not sure if this is a bug or if the documentation has not been updated yet. 

I've currently circumvented the issue by scaling in sklearn (which retains 0s instead of NaNs) and manually loading the scaled results into my adata object as this is the behaviour I would like for my dataset.

In case my example dataset would be helpful let me know then I can share it with you.

**Comment by eroell** [comment] 2024-06-26 13:59
Hey, thanks for the description - yes your example dataset would be very helpful - if you could post a small code snippet here which generates this dataset and shows the specific steps you perform that would be great.

If you cannot produce the dataset in a script, you could also send a link to the dataset (if its public or synthetic, making sure you're allowed to share) :)

In both cases, sending a script here we can run too is a great help!

**Comment by sophiamaedler** [comment] 2024-06-26 14:10
Sure thing. I've dumped a couple of example entries into a numpy file and attached it below as a zip. You can replicate the behaviour with the following code

```
import numpy
import scanpy as sc
import anndata as ad

features = np.load("example_features.npy")

#perform scaling in sklearn
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled = scaler.fit_transform(features.copy())

print(np.isnan(scaled).sum())

#perform scaling in scanpy with the default settings
adata = ad.AnnData(features)
sc.pp.scale(adata)

print(np.isnan(adata.X).sum())
```

For me this results in: 

<img width="477" alt="Screenshot 2024-06-26 at 16 08 41" src="https://github.com/scverse/scanpy/assets/15019107/806d4b70-faf2-4dce-84fc-575cd86c21f6">

[example_features.npy.zip](https://github.com/user-attachments/files/15990483/example_features.npy.zip)

**Comment by eroell** [comment] 2024-07-01 10:26
Thanks, this is very helpful to pinpoint what is happening!

So what's going on here is that within one gene (column), all cells (rows) have the almost same float value.
This causes the variance per gene to be ~0, usually just a tiny value, in this dataset e.g. on the order of 1e-21.
Handling such tiny values, tiny offsets due to numerics can yield negative values for the variance.

When doing np.sqrt() [here](https://github.com/scverse/scanpy/blob/fdfb9a1a48d480a30c23e5f14499a18a6388e418/src/scanpy/preprocessing/_scale.py#L186C5-L186C23) on such a nan, this yields this entire gene column to obtain nans.

From our side, this could be addressed by considering to set such tiny negative values to 0. `sklearn` circumvents this by directly [computing the standard deviation](https://github.com/scikit-learn/scikit-learn/blob/2621573e60c295a435c62137c65ae787bf438e61/sklearn/preprocessing/_data.py#L248) from numpy, which likely has such a mechanism within it directly.

However, trying to "scale" a feature of a constant value should be omitted in the first place very likely: as scaling involves dividing by standard deviation (which is ~0 then), the resulting numbers obtained are not actual biology, but just artifacts from a stability correction.

I'd assume that in scRNAseq, this typically is a gene which is never observed (that is, 0 all the time), and as such could be filtered for in the preprocessing with e.g. `sc.pp.filter_genes(adata, min_counts=...)`, where `a` would be a number > 0.

We might consider to raise a warning here though, as just introducing the nans without further comment can be quite confusing...

What do you think about this @sophiamaedler?

**Comment by sophiamaedler** [comment] 2024-07-01 11:59
Hi @eroell, 
Thanks for looking into this. I think raising a warning would be great before introducing the NaN's. Then it's easier for users to understand what is happening. 

I agree that in most cases it would be better to remove the almost zero values before scaling, so I don't think it would be necessary to implement setting the tiny negative values to 0. While there are some cases where people may want to proceed with this type of data without filtering (like mine e.g. as I am actually working with a curated list of features and not scRNAseq counts) they are scarce and in my opinion sufficiently covered with a warning.
