### ISSUE TITLE
how to perform analysis to get bulk_labels, S_score, G2M_score, phase?

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#744] opened 2019-07-23 06:41 UTC
how to perform analysis to get bulk_labels, S_score, G2M_score, phase?

After following the tutorial "[Clustering 3K PBMCs](https://icb-scanpy-tutorials.readthedocs-hosted.com/en/latest/pbmc3k.html)", I got the object "adata" with following description:
_>>> adata
AnnData object with n_obs × n_vars = 691 × 4549
    **obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain'**
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'_ 

however, the tutorial "[Visualizing marker genes](https://icb-scanpy-tutorials.readthedocs-hosted.com/en/latest/visualizing-marker-genes.html?highlight=%27bulk_labels%27)" use the object "pbmc" with following description:
_>>> adata
AnnData object with n_obs × n_vars = 691 × 4549
    **obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain'**
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'_ 

i want to process my data according those two tutorials and got the figures. but without those information (obs: 'bulk_labels', 'S_score', 'G2M_score', 'phase'), i cannot continue the tutorial from "Clustering 3K PBMCs" to  "Visualizing marker genes"

**Comment by LuckyMD** [comment] 2019-07-23 07:39
duplicate of #745

**Closed as completed** 2019-07-23 07:39 UTC
