### ISSUE TITLE
ImportError: cannot import name 'IndexMixin'

### ISSUE THREAD

**Issue by genecell** [scverse/scanpy#643] opened 2019-05-14 01:46 UTC
Hi,

When I ran
```
import scanpy.api as sc
```
I met this error:
```
     19 from scipy import sparse
     20 from scipy.sparse import issparse
---> 21 from scipy.sparse.sputils import IndexMixin
     22 from natsort import natsorted
     23 

ImportError: cannot import name 'IndexMixin'
```
Is there any requirements for the version of scipy?

Thanks in advance,
BP

**Comment by genecell** [comment] 2019-05-14 02:06
Hi, I just tried install a higher version of scipy, and it works now.
```
pip install scipy==1.2.1
```
Refer to: https://www.scipy.org

**Comment by wir963** [comment] 2019-05-20 16:26
I also ran into this issue when using scanpy==1.4.2 and scipy==1.3.0 (which are the versions installed when I install using conda). Enforcing scipy==1.2.1 in my conda environment file fixed it.

**Comment by bgruening** [comment] 2019-05-21 06:50
This problem also exists in 1.4.3.

**Comment by flying-sheep** [comment] 2019-05-21 07:55
duplicate of theislab/anndata#146

**Closed as duplicate by flying-sheep** 2019-05-21 07:55 UTC

**Comment by levinhein** [comment] 2020-09-14 09:00
Hi. I'm struggling with the same issue that is not resolved with the suggestions above (using other scipy version==1.2.1). I have scanpy==1.6.0 and scipy==1.5.2 in my environment. I am using Ubuntu in Windows.

And when I import scanpy in jupyter notebook, I get the error:

**`ImportError: cannot import name 'IndexMixin' from 'scipy.sparse.sputils' (/home/levinbioinformatics/anaconda3/envs/scgen-env/lib/python3.7/site-packages/scipy/sparse/sputils.py)`**

Please advise!

**Comment by wfma** [comment] 2020-10-23 14:32
I have the same issue as @levinhein!

**Comment by YubinXie** [comment] 2020-11-02 20:39
Same issue here. Downgrading scipy from 1.5.4 to 1.2.1 helps.
