### ISSUE TITLE
Ingest with BBKNN

### ISSUE THREAD

**Issue by martaint** [scverse/scanpy#1108] opened 2020-03-17 09:07 UTC
Hi there! Thanks for adding the ingest method to scanpy!
I was wondering what would be the suggested approach when the reference data contains batch effects that should be removed before actually performing the asymmetric integration with a query dataset. I tried to use the neighbors structure returned by BBKNN (which correctly adjusts for batch effects), but the 'metric' object is missing. Here the error:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-22-a805d117788e> in <module>
----> 1 sc.tl.ingest(adata, adata_ref, obs='time', embedding_method='umap')

/opt/conda/lib/python3.7/site-packages/scanpy/tools/_ingest.py in ingest(adata, adata_ref, obs, embedding_method, labeling_method, inplace, **kwargs)
    115         labeling_method = labeling_method * len(obs)
    116 
--> 117     ing = Ingest(adata_ref)
    118     ing.fit(adata)
    119 

/opt/conda/lib/python3.7/site-packages/scanpy/tools/_ingest.py in __init__(self, adata)
    268 
    269         if 'neighbors' in adata.uns:
--> 270             self._init_neighbors(adata)
    271 
    272         if 'X_umap' in adata.obsm:

/opt/conda/lib/python3.7/site-packages/scanpy/tools/_ingest.py in _init_neighbors(self, adata)
    229         else:
    230             dist_args = ()
--> 231         dist_func = named_distances[adata.uns['neighbors']['params']['metric']]
    232         self._random_init, self._tree_init = make_initialisations(dist_func, dist_args)
    233         self._search = make_initialized_nnd_search(dist_func, dist_args)

KeyError: 'metric'

```
I'm running scanpy version 1.4.5.post2. Any help would be highly appreciated!! Thanks!

**Comment by ivirshup** [comment] 2020-04-17 06:03
Closing as duplicate of #1122.

**Closed as duplicate by ivirshup** 2020-04-17 06:03 UTC
