### ISSUE TITLE
The saving plot had prefix

### ISSUE THREAD

**Issue by honghh2018** [scverse/scanpy#1889] opened 2021-06-20 10:46 UTC
Hi,
    It still had the prefix in plot even though i set the :
    sc.settings.plot_suffix=""
    sc.settings.plot_prefix=""
 The saving plot name like:
    
![image](https://user-images.githubusercontent.com/41668708/122671142-dbd18200-d1f7-11eb-929b-a4e176010f43.png)
how can i fix it?
Best,
hanhuihong

**Comment by honghh2018** [comment] 2021-06-22 05:54
Had anyone hear this?

**Comment by ivirshup** [comment] 2021-06-24 07:45
Closing as duplicate of #1508.

This is the intended current behavior, though we are considering changing it. See previous discussions for more info.

**Closed as duplicate by ivirshup** 2021-06-24 07:45 UTC

**Comment by ACastanza** [comment] 2021-11-08 18:01
Please stop forcing plots to have an unwanted prefix.
