### ISSUE TITLE
Seaborn throws a FutureWarning when using sc.pl.highest_expr_genes

### ISSUE THREAD

**Issue by LinearParadox** [scverse/scanpy#2755] opened 2023-11-15 20:34 UTC
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

When using sc.pl.highest_expr_genes, seaborn throws a FutureWarning. Specifically:

envs/scanpy/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead

### Minimal code sample

```python
sc.pl.highest_expr_genes(adata, n_top=20, )
```

### Error output

```pytb
envs/scanpy/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
```

### Versions

<details>

```
-----
anndata     0.10.3
scanpy      1.9.6
-----
PIL                 10.1.0
asttokens           NA
backcall            0.2.0
comm                0.1.2
cycler              0.12.1
cython_runtime      NA
dateutil            2.8.2
debugpy             1.6.7
decorator           5.1.1
executing           0.8.3
h5py                3.10.0
ipykernel           6.25.0
jedi                0.18.1
joblib              1.3.2
kiwisolver          1.4.5
llvmlite            0.41.1
matplotlib          3.8.1
matplotlib_inline   0.1.6
mpl_toolkits        NA
natsort             8.4.0
numba               0.58.1
numpy               1.26.2
packaging           23.1
pandas              2.1.3
parso               0.8.3
patsy               0.5.3
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
platformdirs        3.10.0
prompt_toolkit      3.0.36
psutil              5.9.0
ptyprocess          0.7.0
pure_eval           0.2.2
pydev_ipython       NA
pydevconsole        NA
pydevd              2.9.5
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pygments            2.15.1
pynndescent         0.5.10
pyparsing           3.1.1
pytz                2023.3.post1
scipy               1.11.3
seaborn             0.12.2
session_info        1.0.0
six                 1.16.0
sklearn             1.3.2
stack_data          0.2.0
statsmodels         0.14.0
threadpoolctl       3.2.0
tornado             6.3.3
tqdm                4.66.1
traitlets           5.7.1
umap                0.5.4
wcwidth             0.2.5
zmq                 25.1.0
-----
IPython             8.15.0
jupyter_client      8.6.0
jupyter_core        5.5.0
-----
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
Linux-6.2.0-1018-gcp-x86_64-with-glibc2.37
-----
Session information updated at 2023-11-15 20:32
```

</details>

**Comment by flying-sheep** [comment] 2023-11-16 08:45
Duplicate of https://github.com/mwaskom/seaborn/issues/3462

**Closed as not planned by flying-sheep** 2023-11-16 08:45 UTC
Labels: Upstream
