### ISSUE TITLE
sinfo is now session_info

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy#1996] opened 2021-09-08 16:02 UTC
https://github.com/theislab/scanpy/blob/63b42e4bff46a9e1386abfede4adeef3a8100c7b/pyproject.toml#L65

> The sinfo package has changed name and is now called session_info to become more discoverable and self-explanatory. The sinfo PyPI package will be kept around to avoid breaking old installs and you can downgrade to 0.3.2 if you want to use it without seeing this message. For the latest features and bug fixes, please install session_info instead. The usage and defaults also changed slightly, so please review the latest README at https://gitlab.com/joelostblom/session_info.

**Comment by flying-sheep** [comment] 2021-12-19 12:38
Duplicate of  #1852

**Closed as duplicate by flying-sheep** 2021-12-19 12:38 UTC
