### ISSUE TITLE
sc.pl.spatial TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by meaksu** [scverse/scanpy#2499] opened 2023-06-03 01:47 UTC
Hi,
I am getting the following error when trying to plot my spatial data

```py
with mpl.rc_context({'axes.facecolor':  'black',
                     'figure.figsize': [4.5, 5]}):
    
    sc.pl.spatial(slide, cmap='magma',
                  color=["AC-like", "Astro", "B_T_NK", "Inhib.neurons", "Micro_Macro", "Neurons", "OC-like", "Oligo", "Pericyte"], 
                  ncols=3, size=1.3, 
                  img_key='hires',
                  # limit color scale at 99.2% quantile of cell abundance
                  vmin=0, vmax='p99.2' 
                 )
```

```pytb
TypeError                                 Traceback (most recent call last)
Cell In[11], line 14
     10 # plot in spatial coordinates
     11 with mpl.rc_context({'axes.facecolor':  'black',
     12                      'figure.figsize': [4.5, 5]}):
---> 14     sc.pl.spatial(slide, cmap='magma',
     15                   # show first 8 cell types
     16                   color=["AC-like", "Astro", "B_T_NK", "Inhib.neurons", "Micro_Macro", "Neurons", "OC-like", "Oligo", "Pericyte"], 
     17                   ncols=3, size=1.3, 
     18                   img_key=None,
     19                   # limit color scale at 99.2% quantile of cell abundance
     20                   vmin=0, vmax='p99.2' 
     21                  )

File ~/.local/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py:993, in spatial(adata, basis, img, img_key, library_id, crop_coord, alpha_img, bw, size, scale_factor, spot_size, na_color, show, return_fig, save, **kwargs)
    990     cmap_img = None
    991 circle_radius = size * scale_factor * spot_size * 0.5
--> 993 axs = embedding(
    994     adata,
    995     basis=basis,
    996     scale_factor=scale_factor,
    997     size=circle_radius,
    998     na_color=na_color,
    999     show=False,
   1000     save=False,
   1001     **kwargs,
   1002 )
   1003 if not isinstance(axs, list):
   1004     axs = [axs]

File ~/.local/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py:169, in embedding(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, neighbors_key, arrows, arrows_kwds, groups, components, layer, projection, scale_factor, color_map, cmap, palette, na_color, na_in_legend, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, vmax, vmin, vcenter, norm, add_outline, outline_width, outline_color, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    165     title = [title] if isinstance(title, str) else list(title)
    167 # get the points position and the components list
    168 # (only if components is not None)
--> 169 data_points, components_list = _get_data_points(
    170     adata, basis, projection, components, scale_factor
    171 )
    173 # Setup layout.
    174 # Most of the code is for the case when multiple plots are required
    175 # 'color' is a list of names that want to be plotted.
    176 # Eg. ['Gene1', 'louvain', 'Gene2'].
    177 # component_list is a list of components [[0,1], [1,2]]
    178 if (
    179     not isinstance(color, str)
    180     and isinstance(color, cabc.Sequence)
    181     and len(color) > 1
    182 ) or len(components_list) > 1:

File ~/.local/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py:1130, in _get_data_points(adata, basis, projection, components, scale_factor)
   1127     components_list = []
   1129 if scale_factor is not None:  # if basis need scale for img background
-> 1130     data_points[0] = np.multiply(data_points[0], scale_factor)
   1132 return data_points, components_list

TypeError: can't multiply sequence by non-int of type 'float'
```

It looks like the scale.factor for the hires image key is a float: 'tissue_hires_scalef': 0.12813942
Do you know what can be modified so that the data is plottable?

**Comment by flying-sheep** [comment] 2023-06-13 10:06
Hmm, that sounds like the code is trying to do something like `['a', 'b'] * 1.5`, i.e. repeating a sequence by multiplying.

But the line the error points to looks correct: `np.multiply` should try to do element-wise multiplication as intended.

Please create a minimal reproducible example. We don’t know what in `slide` causes the bug because we don’t know what it is.

**Comment by meaksu** [comment] 2023-06-21 20:17
Hi,
Sorry I'm not exactly sure how to create a reproducible example. Is there a way I can share the h5ad object with you?

**Comment by RaphaelBuzzi** [comment] 2023-06-22 07:39
Do the data come from an FFPE 10X Visium experiment calculated with the SpaceRanger version 2.1?

How does the tisue_position_list.csv within the spatial folder of the SpaceRanger output look?
Maybe you could attach a screenshot or the csv.-file. (try drag and drop)

**Comment by flying-sheep** [comment] 2023-06-22 10:15
If the data isn’t sensitive, just share the .h5ad file with us in any way.

if it is, you’d need to write code like this:

```py
ad = AnnData(np.random.rand(10, 20), obs={...}, uns={...})
```

with just the necessary pieces to make the bug appear.

**Comment by meaksu** [comment] 2023-06-25 01:44
Hi,
The data comes from FFPE 10x Visium but Spaceranger version 2.0.0

I attached the csv file here
[tissue_positions_list.csv](https://github.com/scverse/scanpy/files/11858496/tissue_positions_list.csv)

I also just emailed the h5ad file

**Comment by RaphaelBuzzi** [comment] 2023-06-26 05:41
Thanks for the file.

For the FFPE 10X Visium, the Spaceranger includes a header for the tissue_positions_list.csv file. This seems not to be recognized by the scanpy.read_spatial function during import.

Quickfix: delete the header and try importing and plotting again.

@flying-sheep Could this be fixed withing the scanpy function in the future?

**Comment by flying-sheep** [comment] 2023-06-26 09:30
I see! File looks like this:

```csv
barcode,in_tissue,array_row,array_col,pxl_row_in_fullres,pxl_col_in_fullres
GTCACTTCCTTCTAGA-1,0,0,0,-1567,2629
CACGGTCTCCTTACGA-1,0,0,2,-1569,2811
ATAGCTGCGGATAAGA-1,0,0,4,-1571,2993
GTCAGTATGTCCGGCG-1,0,0,6,-1573,3174
...
```

@RaphaelBuzzi you mean `read_visium`, right? There is no `read_spatial` in scanpy.

That one seems to assume that
- if the file is called `tissue_positions.csv`, it has a header on the second row (index 1), and
- if it is called `tissue_positions_list.csv`, it has no header line:

https://github.com/scverse/scanpy/blob/692c9e536ab1d3b0a7d16e9c2c6e7d53390f9b5a/scanpy/readwrite.py#L461-L465

The only thing that looks weird about that is the index 1 instead of 0, otherwise it looks identical to the PR by 10x: https://github.com/satijalab/seurat/pull/6208/files

So the question is: why is there a file called `tissue_positions_list.csv` that has a header? That doesn’t seem like what 10x’s pipeline does.

**Closed as not planned** 2023-06-26 09:33 UTC
Labels: Area – Spatial 🗺, Area - IO

**Comment by RaphaelBuzzi** [comment] 2023-06-26 10:53
> @RaphaelBuzzi you mean `read_visium`, right? There is no `read_spatial` in scanpy.

Yes, I meant read_visium.

If I use read_visium (using scanpy version 1.9.1) I get the following OSerror:
`OSError: Could not find 'spatial/tissue_positions_list.csv'`

Is the usage of read_visium only implemented in version 1.9.2?

**Comment by flying-sheep** [comment] 2023-06-26 11:03
It’s actually still unreleased. We should release 1.9.3 soon!

**Comment by RaphaelBuzzi** [comment] 2023-06-26 11:25
So we still need to perform the following work around:
1) change file name of file `tissue_positions.csv` to `tissue_positions_list.csv`
2) delete the header in the file

Right?

**Comment by flying-sheep** [comment] 2023-06-26 11:40
Or you install the development version of scanpy: `pip install git+https://github.com/scverse/scanpy.git`
