### ISSUE TITLE
Again: NameError: name 'NeighborsView' is not defined when export spring project

### ISSUE THREAD

**Issue by AlejandraRodelaRo** [scverse/scanpy#1285] opened 2020-06-17 14:14 UTC
When exporting a SPRING project I get the following error (NameError: name 'NeighborsView' is not defined ). 16 days ago a bug issue was closed related to this ( #1260  ), however I still encounter the bug when using both Scanpy 1.5.1 or 1.5.0; 

**Input**:
```import time
t0 = time.time()
sc.external.exporting.spring_project(adata, './SPRING',
                            'umap', subplot_name='all', overwrite=True, cell_groupings=['leiden'],
                                    custom_color_tracks=['total_counts'])
print(time.time() - t0)
```

**Output**: 
```Writing subplot to SPRING\all
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-59-9c683583ff59> in <module>
      1 import time
      2 t0 = time.time()
----> 3 sc.external.exporting.spring_project(adata, './SPRING',
      4                             'umap', subplot_name='all', overwrite=True, cell_groupings=['leiden'],
      5                                     custom_color_tracks=['total_counts'])

~\Anaconda3\envs\sfn-workshop\lib\site-packages\scanpy\external\exporting.py in spring_project(adata, project_dir, embedding_method, subplot_name, cell_groupings, custom_color_tracks, total_counts_key, neighbors_key, overwrite)
    179 
    180     # Write graph in two formats for backwards compatibility
--> 181     edges = _get_edges(adata, neighbors_key)
    182     _write_graph(subplot_dir / 'graph_data.json', E.shape[0], edges)
    183     _write_edges(subplot_dir / 'edges.csv', edges)

~\Anaconda3\envs\sfn-workshop\lib\site-packages\scanpy\external\exporting.py in _get_edges(adata, neighbors_key)
    217 
    218 def _get_edges(adata, neighbors_key=None):
--> 219     neighbors = NeighborsView(adata, neighbors_key)
    220     if 'distances' in neighbors:  # these are sparse matrices
    221         matrix = neighbors['distances']

NameError: name 'NeighborsView' is not defined
```

#### AnnData: 
```AnnData object with n_obs × n_vars = 2638 × 1838
    obs: 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'leiden'
    var: 'gene_ids', 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'
```

#### Versions:
scanpy==1.5.1 anndata==0.7.3 umap==0.4.3 numpy==1.18.4 scipy==1.3.2 pandas==1.0.4 scikit-learn==0.23.1 statsmodels==0.11.1 python-igraph==0.8.2 leidenalg==0.8.0

**Comment by Koncopd** [comment] 2020-06-26 10:12
Hi, @AlejandraRodelaRo 
It was fixed on github master. You can wait for a new release or install scanpy from github.

**Comment by PattF** [comment] 2020-07-19 11:13
Hi @Koncopd, any idea when the new release will be out?

**Comment by flying-sheep** [comment] 2020-07-20 12:30
Yes, this is a duplicate of #1260. Please follow #1319 to track the next release

**Closed as duplicate by flying-sheep** 2020-07-20 12:30 UTC
