### ISSUE TITLE
highly_variable_genes with batch_key results in a "division by zero" error, if there is a batch with a single sample

### ISSUE THREAD

**Issue by YochayTzur** [scverse/scanpy#3103] opened 2024-06-09 09:43 UTC
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

When running highly_variable_genes with batch_key input, and the data contains batch with only one sample (due to earlier filtering) the computation failed, returning "division by zero" error. 
The expected behavior is to ignore this batch (a single sample).

### Minimal code sample

```python
#Create dummy anndata with batch key. Batch 3 contains 1 sample.
test_ad = ad.AnnData(X=np.random.randn(10,100), 
                     obs=pd.DataFrame({'batch':pd.Categorical([1,1,1,1,2,2,2,2,2,3])}))
#This works fine
sc.pp.highly_variable_genes(test_ad)

#This returns division by zero error
#sc.pp.highly_variable_genes(test_ad, batch_key='batch')
```

### Error output

```pytb
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[41], line 11
      9 with warnings.catch_warnings():  #ignore future_warning in groupby
     10     warnings.simplefilter(action='ignore', category=FutureWarning)
---> 11     sc.pp.highly_variable_genes(adata_ct, batch_key='sample_id', n_top_genes=hvg_count)
     12 sc.pl.highly_variable_genes(adata_ct)

File ~/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:469, in highly_variable_genes(adata, layer, n_top_genes, min_disp, max_disp, min_mean, max_mean, span, n_bins, flavor, subset, inplace, batch_key, check_values)
    465     filt = filter_genes(adata_subset, min_cells=1, inplace=False)[0]
    467 adata_subset = adata_subset[:, filt]
--> 469 hvg = _highly_variable_genes_single_batch(
    470     adata_subset,
    471     layer=layer,
    472     min_disp=min_disp,
    473     max_disp=max_disp,
    474     min_mean=min_mean,
    475     max_mean=max_mean,
    476     n_top_genes=n_top_genes,
    477     n_bins=n_bins,
    478     flavor=flavor,
    479 )
    481 # Add 0 values for genes that were filtered out
    482 missing_hvg = pd.DataFrame(
    483     np.zeros((np.sum(~filt), len(hvg.columns))),
    484     columns=hvg.columns,
    485 )

File ~/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:206, in _highly_variable_genes_single_batch(adata, layer, min_disp, max_disp, min_mean, max_mean, n_top_genes, n_bins, flavor)
    203     else:
    204         X = np.expm1(X)
--> 206 mean, var = materialize_as_ndarray(_get_mean_var(X))
    207 # now actually compute the dispersion
    208 mean[mean == 0] = 1e-12  # set entries equal to zero to small value

File ~/lib/python3.10/site-packages/scanpy/preprocessing/_utils.py:14, in _get_mean_var(X, axis)
     12     var = mean_sq - mean**2
     13 # enforce R convention (unbiased estimator) for variance
---> 14 var *= X.shape[axis] / (X.shape[axis] - 1)
     15 return mean, var

ZeroDivisionError: division by zero
```

### Versions

<details>

```
anndata     0.10.3
scanpy      1.9.6
```

</details>

**Comment by linlejiang** [comment] 2024-07-09 14:40
I have an exact same error as well. By dropping one of the samples the issue was gone. Any ideas?

**Comment by flying-sheep** [comment] 2024-10-15 12:35
Duplicate of #2236, please follow there for updates

**Closed as duplicate by flying-sheep** 2024-10-15 12:35 UTC
