### ISSUE TITLE
Gene filtering using sparse matrix error

### ISSUE THREAD

**Issue by rbf22** [scverse/scanpy#1354] opened 2020-08-03 05:15 UTC
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

### Minimal code sample (that we can copy&paste without having any data)

```python
sc.pp.filter_genes(adata, min_cells=10)
# with <3298x24714 sparse matrix of type '<class 'numpy.float32'>'
#    with 11965294 stored elements in Compressed Sparse Row format>
```

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-431c88656c87> in <module>
----> 1 sc.pp.filter_genes(adata, min_cells=3, max_cells=None)

/usr/local/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py in filter_genes(data, min_counts, min_cells, max_counts, max_cells, inplace, copy)
    216             filter_genes(adata.X, min_cells=min_cells,
    217                          min_counts=min_counts, max_cells=max_cells,
--> 218                          max_counts=max_counts))
    219         if not inplace:
    220             return gene_subset, number

/usr/local/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py in filter_genes(data, min_counts, min_cells, max_counts, max_cells, inplace, copy)
    230     max_number = max_counts if max_cells is None else max_cells
    231     number_per_gene = np.sum(X if min_cells is None and max_cells is None
--> 232                              else X > 0, axis=0)
    233     if issparse(X):
    234         number_per_gene = number_per_gene.A1

TypeError: '>' not supported between instances of 'SparseDataset' and 'int'
```

#### Versions

<details>

scanpy==1.5.1 anndata==0.7.4 umap==0.4.6 numpy==1.18.5 scipy==1.5.2 pandas==1.0.4 scikit-learn==0.23.1 statsmodels==0.11.1

</details>

**Comment by rbf22** [comment] 2020-08-03 05:36
This seems like it is a known issue: theislab/scanpy#650
There is a semi-related issue here too: theislab/anndata#179

**Comment by flying-sheep** [comment] 2020-08-03 07:17
Yeah, SparseDataset means this is a duplicate of #650. And yes, we should definitely get theislab/anndata#179 in!

**Closed as duplicate** 2020-08-03 07:17 UTC
