### ISSUE TITLE
Scanpy Shouldn't Append Writekey by Defualt

### ISSUE THREAD

**Issue by jwalewski** [scverse/scanpy#2674] opened 2023-09-29 14:40 UTC
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Hello,

After using Cellrank, a program that requires scanpy, on a computing cluster, I realized I was having issues with the saving of my figures due to the behavior caused by line 311 of scanpy/plotting/_utils.py - writekey _appends_ the filepath the user provides instead of _using_ it. 

Since a lot of bioinformatics is done on cluster computing, where many users may not have permissions to create new directories, this feature should be optional. It should be up to the user to fully determine they filepath they wise to use IMO - would it be possible to implement new default functionality? I can create a pull request if that makes it easier.

Many thanks for your consideration.

**Comment by Zethson** [comment] 2023-10-31 15:55
Duplicate of https://github.com/scverse/scanpy/issues/2324

**Comment by Zethson** [comment] 2023-10-31 15:56
@jwalewski I personally would appreciate such a PR and would love to see this behavior changed (I also fell into this trap), but I'd like another opinion from @ivirshup or @flying-sheep

**Closed as completed by Zethson** 2023-10-31 15:55 UTC
