### ISSUE TITLE
macOS matplotlib error

### ISSUE THREAD

**Issue by kt6k** [scverse/scanpy#567] opened 2019-03-28 16:43 UTC
2019-03-28 12:33:23.060 python[7387:245759] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb4fdc7cfb0
2019-03-28 12:33:23.065 python[7387:245759] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb4fdc7cfb0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff44fd3ded __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7109b720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff45051195 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff44f75a60 ___forwarding___ + 1486
	4   CoreFoundation                      0x00007fff44f75408 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000001a278cc31d TkpInit + 413
	6   libtk8.6.dylib                      0x0000001a2782417e Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x0000001a2764ca0f _tkinter_create + 1183
	8   python                              0x000000010a42d8b6 _PyMethodDef_RawFastCallKeywords + 230
	9   python                              0x000000010a56db47 call_function + 247
	10  python                              0x000000010a56b684 _PyEval_EvalFrameDefault + 45284
	11  python                              0x000000010a55f2d2 _PyEval_EvalCodeWithName + 418
	12  python                              0x000000010a42c577 _PyFunction_FastCallDict + 231
	13  python                              0x000000010a4b00b1 slot_tp_init + 193
	14  python                              0x000000010a4ba091 type_call + 241
	15  python                              0x000000010a42d283 _PyObject_FastCallKeywords + 179
	16  python                              0x000000010a56dbe4 call_function + 404
	17  python                              0x000000010a56b778 _PyEval_EvalFrameDefault + 45528
	18  python                              0x000000010a42d078 function_code_fastcall + 120
	19  python                              0x000000010a56dafe call_function + 174
	20  python                              0x000000010a56b684 _PyEval_EvalFrameDefault + 45284
	21  python                              0x000000010a55f2d2 _PyEval_EvalCodeWithName + 418
	22  python                              0x000000010a42c577 _PyFunction_FastCallDict + 231
	23  python                              0x000000010a4304a2 method_call + 130
	24  python                              0x000000010a42def2 PyObject_Call + 130
	25  python                              0x000000010a56b8cf _PyEval_EvalFrameDefault + 45871
	26  python                              0x000000010a55f2d2 _PyEval_EvalCodeWithName + 418
	27  python                              0x000000010a42c577 _PyFunction_FastCallDict + 231
	28  python                              0x000000010a56b8cf _PyEval_EvalFrameDefault + 45871
	29  python                              0x000000010a55f2d2 _PyEval_EvalCodeWithName + 418
	30  python                              0x000000010a42c577 _PyFunction_FastCallDict + 231
	31  python                              0x000000010a56b8cf _PyEval_EvalFrameDefault + 45871
	32  python                              0x000000010a55f2d2 _PyEval_EvalCodeWithName + 418
	33  python                              0x000000010a42c577 _PyFunction_FastCallDict + 231
	34  python                              0x000000010a4b00b1 slot_tp_init + 193
	35  python                              0x000000010a4ba091 type_call + 241
	36  python                              0x000000010a42d283 _PyObject_FastCallKeywords + 179
	37  python                              0x000000010a56dbe4 call_function + 404
	38  python                              0x000000010a56b778 _PyEval_EvalFrameDefault + 45528
	39  python                              0x000000010a55f2d2 _PyEval_EvalCodeWithName + 418
	40  python                              0x000000010a42d783 _PyFunction_FastCallKeywords + 195
	41  python                              0x000000010a56dafe call_function + 174
	42  python                              0x000000010a56b778 _PyEval_EvalFrameDefault + 45528
	43  python                              0x000000010a55f2d2 _PyEval_EvalCodeWithName + 418
	44  python                              0x000000010a5c3c40 PyRun_FileExFlags + 256
	45  python                              0x000000010a5c30b7 PyRun_SimpleFileExFlags + 391
	46  python                              0x000000010a5ef7ec pymain_main + 9564
	47  python                              0x000000010a3ffa9d main + 125
	48  libdyld.dylib                       0x00007fff72169ed9 start + 1
	49  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by ivirshup** [comment] 2019-03-29 01:38
Not sure we can do a lot with just a traceback. Could you create a [minimal example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to reproduce this error, and describe what you were trying to do?

**Comment by kt6k** [comment] 2019-04-01 16:33
Hi. Please see below for the minimal script used. Thanks!

```python
import numpy as np
import pandas as pd
import scanpy as sc
import scvelo as scv
import matplotlib.pyplot as plt
from pathlib import Path

scv.settings.set_figure_params('scvelo')

sc.settings.verbosity = 3  # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.settings.autosave = True
sc.settings.autoshow = False
sc.set_figure_params(scanpy=True, dpi=80, dpi_save=160, frameon=False, vector_friendly=False, format='pdf')

adata = sc.read_loom("./Velocyto_comb.loom")

sc.pp.filter_cells(adata, min_genes=1000)
sc.pp.filter_genes(adata, min_cells=10)

print('\nDoing initial filtering...\nKeeping', len(adata.obs_names), 'cells and', len(adata.var_names), 'genes.\n')

mito_genes = adata.var_names.str.startswith('MT-')
# Calculate the percent of genes derived from mito vs genome
# the `.A1` is only necessary as X is sparse (to transform to a dense array after summing)
adata.obs['percent_mito'] = np.sum(
	adata[:, mito_genes].X, axis=1).A1 / np.sum(adata.X, axis=1).A1
# add the total counts per cell as observations-annotation to adata
adata.obs['n_counts'] = adata.X.sum(axis=1).A1

sc.pl.violin(adata, ['n_genes', 'n_counts', 'percent_mito'],
			 jitter=0.4, multi_panel=True, save = '_preFiltering_plot.pdf', show = False)
```

**Comment by ivirshup** [comment] 2019-04-02 00:29
Would you mind reading through the link I sent and cutting this back?

This doesn't fit the "reproducible" criteria (I don't have that data file), and I'm not sure which line actually causes the error.

**Comment by ivirshup** [comment] 2019-04-03 05:36
Actually, no need to post more. A labmate managed to find this too. It looks like it has something to do with Matplotlib and the `TkAgg` backend (see: https://github.com/matplotlib/matplotlib/issues/13414).

While this error doesn't occur in my normal environment, I can reproduce this error in a conda environment:

```sh
conda create -yn conda_scanpy scanpy
conda activate conda_scanpy
python -c "import matplotlib.pyplot as plt; plt.figure()"
```

We were able to get plotting to work by switching to the `Agg` backend. You can do this by adding the following lines to the top of your script:

```python
import matplotlib as mpl
mpl.use("Agg")
```

**Comment by ivirshup** [comment] 2019-04-03 06:03
@kt6k were you using a conda environment when you hit this error?

**Comment by kt6k** [comment] 2019-05-01 03:06
Thank you for your response. Yes,
using Miniconda3-latest-MacOSX-x86_64.pkg. I keep encountering additional
errors. Is there a better environment? Thanks!

**Comment by kt6k** [comment] 2019-05-01 03:37
Yes, using Miniconda3-latest-MacOSX-x86_64.pkg. Your fix worked out. Thanks!

**Comment by kt6k** [comment] 2019-05-07 03:18
Hi ivisrup. This may already have been discussed elsewhere (or I could open a new issue)...

It appears that I am loosing a bunch of genes/transcripts during the Velocyto analysis, and I am trying to figure out what is going on. After running Velocyto, there are approximately 5000 final filtered transcripts (presumably ones used for the vector calculation). However, several genes/transcripts of interest that should be highly expressed in most cells (seen using software like Seurat) are not listed in the final filtered genes. Thus, I am suspecting that many genes/transcripts are, for some reason, being lost during Velocyto calculation. 

Does Velocyto filter out genes that are not differentially expressed (namely, genes/transcripts that are not useful to plot vector)?

My cells are captured using Fluidigm. 

Could you please (if possible) elaborate on this? Very much appreciated.

**Comment by ivirshup** [comment] 2019-05-07 04:56
@kt6k, I think that's worth opening a separate issue for. I'm not too experienced with the velocyto tools, but I suspect the issue might be more appropriate for either [velocyto-team/velocyto.py](https://github.com/velocyto-team/velocyto.py) or [theislab/scvelo](https://github.com/theislab/scvelo) depending on when this filtering is occurring.

**Comment by Zethson** [comment] 2023-01-04 12:37
Closing because the issue should be tracked elsewhere.

**Closed as completed by Zethson** 2023-01-04 12:37 UTC
