### ISSUE TITLE
read_10x_mtx() with annData 0.10.4 only reads one variable

### ISSUE THREAD

**Issue by lelandwilliams** [scverse/scanpy#2825] opened 2024-01-24 20:51 UTC
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

After upgrading annData to 0.10.4 I tried to read in some Visium data with read_10x_mtx()
The resulting table only had one variable (/gene/column), and had it over and over again.

### Minimal code sample

```python
S = scanpy.read_10x_mtx(mydata)
```

### Error output

```pytb
/home/lhw/pkgs/mambaforge/envs/env2/lib/python3.11/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [6]: S.var_names
Out[6]: 
Index(['NOC2L', 'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L',
       'NOC2L', 'NOC2L',
       ...
       'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L', 'NOC2L',
       'NOC2L', 'NOC2L'],
      dtype='object', length=18085)

To test, I ran in another environment with scanpy 1.9.6 but annData 0.10.3.
Below are the results:

In [4]: S = scanpy.read_10x_mtx(mydata)

In [5]: S.var_names
Out[5]: 
Index(['SAMD11', 'NOC2L', 'KLHL17', 'PLEKHN1', 'PERM1', 'HES4', 'ISG15',
       'AGRN', 'RNF223', 'C1orf159',
       ...
       'MT-ND2', 'MT-CO2', 'MT-ATP6', 'MT-CO3', 'MT-ND3', 'MT-ND4L', 'MT-ND4',
       'MT-ND5', 'MT-ND6', 'MT-CYB'],
      dtype='object', length=18085)
```

### Versions
Scanpy 1.9.6
annData 0.10.3 works, annData 0.10.4 does not
<details>

```

```

</details>

**Comment by flying-sheep** [comment] 2024-01-25 08:27
Duplicate of #2806

Please check recently closed issues, I *just* closed #2822 as a duplicate

**Closed as not planned by flying-sheep** 2024-01-25 08:27 UTC
