### ISSUE TITLE
pl.rank_genes_groups_violin() throws a KeyError when gene_symbols  option is passed

### ISSUE THREAD

**Issue by riederd** [scverse/scanpy#2540] opened 2023-06-28 16:06 UTC
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

When trying to produce a violin plot using `pl.rank_genes_groups_violin()` of the ranked genes and passing `gene_symbols="gene_symbols"` I get a `KeyError`. However `pl.rank_genes_groups()` works fine with the option `gene_symbols="gene_symbols"`  and the same `adata` object.

### Minimal code sample

```python
sc.pl.rank_genes_groups_violin(
        adata, groups=cell_types, n_genes=15, strip=False, gene_symbols="gene_symbols"
)
```

### Error output

```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[258], line 1
----> 1 sc.pl.rank_genes_groups_violin(
      2     adata, groups=cell_types, n_genes=15, strip=False, gene_symbols="gene_symbols"
      3 )

File ~/.conda/envs/scirpy/lib/python3.10/site-packages/scanpy/plotting/_tools/__init__.py:1157, in rank_genes_groups_violin(adata, groups, n_genes, gene_names, gene_symbols, use_raw, key, split, scale, strip, jitter, size, ax, show, save)
   1155 if isinstance(_gene_names, np.ndarray):
   1156     _gene_names = _gene_names.tolist()
-> 1157 df = obs_df(adata, _gene_names, use_raw=use_raw, gene_symbols=gene_symbols)
   1158 new_gene_names = df.columns
   1159 df['hue'] = adata.obs[groups_key].astype(str).values

File ~/.conda/envs/scirpy/lib/python3.10/site-packages/scanpy/get/get.py:272, in obs_df(adata, keys, obsm_keys, layer, gene_symbols, use_raw)
    269 else:
    270     alias_index = None
--> 272 obs_cols, var_idx_keys, var_symbols = _check_indices(
    273     adata.obs,
    274     var.index,
    275     "obs",
    276     keys,
    277     alias_index=alias_index,
    278     use_raw=use_raw,
    279 )
    281 # Make df
    282 df = pd.DataFrame(index=adata.obs_names)

File ~/.conda/envs/scirpy/lib/python3.10/site-packages/scanpy/get/get.py:167, in _check_indices(dim_df, alt_index, dim, keys, alias_index, use_raw)
    165         not_found.append(key)
    166 if len(not_found) > 0:
--> 167     raise KeyError(
    168         f"Could not find keys '{not_found}' in columns of `adata.{dim}` or in"
    169         f" {alt_repr}.{alt_search_repr}."
    170     )
    172 return col_keys, index_keys, index_aliases

KeyError: "Could not find keys '['ENSMUSG00000003420', 'ENSMUSG00000022584', 'ENSMUSG00000024910', 'ENSMUSG00000028495', 'ENSMUSG00000032446', 'ENSMUSG00000035042', 'ENSMUSG00000045777', 'ENSMUSG00000051354', 'ENSMUSG00000054206', 'ENSMUSG00000056209', 'ENSMUSG00000056290', 'ENSMUSG00000057113', 'ENSMUSG00000057329', 'ENSMUSG00000064023', 'ENSMUSG00000076461']' in columns of `adata.obs` or in adata.raw.var['gene_symbols']."
```

### Versions

<details>

```
-----
anndata     0.9.1
scanpy      1.9.3
-----
Levenshtein                 0.21.0
PIL                         9.5.0
adjustText                  NA
airr                        1.4.1
asttokens                   NA
awkward                     2.2.2
awkward_cpp                 NA
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
brotli                      NA
certifi                     2023.05.07
cffi                        1.15.1
charset_normalizer          3.1.0
colorama                    0.4.6
comm                        0.1.3
cycler                      0.10.0
cython_runtime              NA
dateutil                    2.8.2
debugpy                     1.6.7
decorator                   5.1.1
executing                   1.2.0
h5py                        3.8.0
hypergeom_ufunc             NA
idna                        3.4
igraph                      0.10.4
invgauss_ufunc              NA
ipykernel                   6.22.0
ipywidgets                  8.0.6
jedi                        0.18.2
joblib                      1.2.0
kiwisolver                  1.4.4
leidenalg                   0.9.1
llvmlite                    0.39.1
matplotlib                  3.7.1
matplotlib_inline           0.1.6
mpl_toolkits                NA
mudata                      0.2.3
muon                        0.1.5
natsort                     8.3.1
nbinom_ufunc                NA
ncf_ufunc                   NA
nct_ufunc                   NA
ncx2_ufunc                  NA
networkx                    3.1
numba                       0.56.4
numpy                       1.23.5
packaging                   23.1
pandas                      1.5.3
parso                       0.8.3
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
platformdirs                3.2.0
pooch                       v1.7.0
prompt_toolkit              3.0.38
psutil                      5.9.5
ptyprocess                  0.7.0
pure_eval                   0.2.2
pycparser                   2.21
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.9.5
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.15.1
pynndescent                 0.5.10
pyparsing                   3.0.9
pytz                        2023.3
rapidfuzz                   2.15.1
requests                    2.28.2
scipy                       1.10.1
scirpy                      0.13.1.dev2+g4ed908b
seaborn                     0.12.2
session_info                1.0.0
setuptools                  67.7.1
six                         1.16.0
skewnorm_ufunc              NA
sklearn                     1.2.2
socks                       1.7.1
squarify                    NA
stack_data                  0.6.2
statsmodels                 0.13.5
texttable                   1.6.7
threadpoolctl               3.1.0
torch                       1.12.1.post201
tornado                     6.3
tqdm                        4.65.0
tracerlib                   NA
traitlets                   5.9.0
typing_extensions           NA
umap                        0.5.3
urllib3                     1.26.15
wcwidth                     0.2.6
yaml                        6.0
yamlordereddictloader       NA
zmq                         25.0.2
zoneinfo                    NA
-----
IPython             8.13.2
jupyter_client      8.2.0
jupyter_core        5.3.0
-----
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-glibc2.17
-----
Session information updated at 2023-06-28 18:02
```

</details>

**Comment by flying-sheep** [comment] 2023-06-29 08:18
can you please update your code sample so we can just copy and paste it? There’s an `import scanpy as ac` and a `adata = ???` missing

**Comment by riederd** [comment] 2023-06-29 10:15
Here we go:

```py
import scanpy as sc


from pathlib import Path
import ssl
import urllib.request

adata_file = "test_adata.h5ad"

if not Path(adata_file).exists():
    ssl._create_default_https_context = ssl._create_unverified_context
    urllib.request.urlretrieve("https://apps-01.i-med.ac.at/resources/tmp/toy_adata.h5ad", adata_file)

adata = sc.read_h5ad(adata_file)


t_celltypes = ["Naive CD4+ T cells", "Naive CD8+ T cells"]
sc.tl.rank_genes_groups(
    adata,
    groupby="cell_type",
    groups=t_celltypes,
    reference="rest",
    method="wilcoxon",
)


# This works
sc.pl.rank_genes_groups(
    adata, groups=t_celltypes, n_genes=15, strip=False, gene_symbols="gene_symbols"
)

# We get the KeyError here
sc.pl.rank_genes_groups_violin(
    adata, groups=t_celltypes, n_genes=15, strip=False, gene_symbols="gene_symbols"
)
```

**Comment by flying-sheep** [comment] 2023-07-07 14:04
Ah, this is a duplicate of #2258, please subscribe there!

someone in a linked issue said that `use_raw=True` can help, but we’ll nevertheless fix this.

**Closed as not planned by flying-sheep** 2023-07-07 14:04 UTC
Labels: Area - Plotting 🌺
